apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "deluge.fullname" . }}-config-pv
spec:
  capacity:
   storage: {{ .Values.storage.configSize }}
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: {{ include "deluge.fullname" . }}-config-pvc
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: delugevolume1  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: xxx.xxx.xxx.xxx ## replace with your nfs server ip address
      share: ## NFS server share path
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "deluge.fullname" . }}-download-pv
spec:
  capacity:
   storage: {{ .Values.storage.downloadSize }}
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: {{ include "deluge.fullname" . }}-download-pvc
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: delugevolume2  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: xxx.xxx.xxx.xxx ## replace with your nfs server ip address
      share: ## NFS server share path