kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "deluge.fullname" . }}-config-pvc
  namespace: homenet
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ include "deluge.fullname" . }}-config-pv
  resources:
    requests:
      storage: {{ .Values.storage.configSize }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "deluge.fullname" . }}-download-pvc
  namespace: homenet
spec:
  accessModes:
    - ReadWriteMany
  volumeName: {{ include "deluge.fullname" . }}-download-pv
  resources:
    requests:
      storage: {{ .Values.storage.downloadSize }}